### PR TITLE
Update tacking.py

### PR DESCRIPTION
**Pull request by akakniven**
Tacking in wind mode was at best unpredictable, the changes have been tested ok in moderate wind.

### CODE REVIEW

**Comment by seandepagnier** [comment]
It seems you are using the sensor value directly rather than the gyro and compass compensated wind direction, why does this help?

Are you sure the direction is correct?

**Comment by akakniven** [comment]
The code in my pull-request has been tested upwind in 15 knots. See linked photos. 
https://photos.app.goo.gl/wDEAgeXBzFjrHQ9R7

You are mentioning the gyro and compass compensated wind direction... Is that the variable called heading? 
heading = ap.boatimu.SensorValues['heading_lowpass'].value

To me, that looks like the compass heading, which is fine in compass mode, but somewhat irrelevant in (apparent) wind mode...

Regarding the direction and sign convention, I agree that there are some non-intuitive issues in the code. I should have kept some of the logging output, but it appears to me that the winddir (current apparent wind direction) and the command (desired wind direction after the tack) have opposite signs. So a more explicit way of expressing line 153 would be 
`d = 0.5 * ( 1 + winddir / (- command)).
Nonetheless, my understanding of the d-variable is that it should start out at zero, and grow gradually until the tack threshold criteria is met, typically 60% of the tack to complete.`

**Comment by akakniven** [comment]
Screenshot 2023-09-25 125836

**Comment by seandepagnier** [comment]
I merged a bunch of changes and hopefully support jibing too now.

**Pull request closed without merging**
