### PR TITLE
Added esp32 remote Touchpad support

### PR DESCRIPTION
**Pull request by kagouraki**
I added support for the touchpins on the esp in order to avoid the pushbuttons and build a more simple pcb. Also it is easier to waterproof if you have touchpads instead of pushbuttons.

i also added a folder in the hat directory to include the micropython .bin file and some instructions.

### CODE REVIEW

**Comment by seandepagnier** [comment]
Thanks for the contribution.   I need to set it up a bit better so it doesn't break existing boards that dont use touch pin.   You can see there are two types of boards supported..  the test of how much memory is may be not the best way to distinguish them but what is used.    Perhaps a simple variable set in the config or even in just that file to leave the existing assignments?   That board has a way to completely power down to if gpio 26 is triggered, and requires the user to press a key to wake again, but you probably dont have this.

As for the binary...  I dont want binary files in git.   It really slows things down especially for cloning.  It could be in an alternate repository or hosted somewhere.   I will try to put the commit hash in the readme to help reproduce it.

**Comment by kagouraki** [comment]
No i dont want power of and dont see whats the point of it.

My commit doesnt break anything. If you leave the keypad_touch array empty the code behaves as the original one.

As of the binary you are write. I found your micropython branch m1_14 and i will try to compile it today. 
It was my fault actually, i didnt know that there are branches in the repos... i founded out yesterday when i was making the pull request following a youtube tutorial ha ha ha ha

**Comment by seandepagnier** [comment]
The point of power is to shut down to 0.1uA of current draw from the battery.    This is useful if you have a small lithium battery powering it.    Pressing the auto key wakes up the remote control.   There is no way to get power draw that low without external mosfets which is what I use, and that pin controls it.

Do you need me to modify the changes so they don't break anything?

**Comment by kagouraki** [comment]
I dont understand where it can break something. If you leave the keypad_touch array empty the code works as yours original. If you have entries in the keypad_touch array then, only these pins are polled on each call of def poll(lcd). All others have interrupt as normal. 
In your original code, if one of the pin cant set an interrupt all of them are polled on each call of def poll(lcd). 
I looked it over and over and i dont see where it will break. But by any means. You are FAR more expierienced than me so change what do you believe is correct. 
I spend 10 hours figuring and writing everything and i wanted to share. If it is not correct, i have no problem. My main concern is to learn not to contribute. So your are free to make what you believe is best. I trust you because you are awesome ! ! ! 
Also through searching i came across a function that wake the esp through a touchpad. I cant find it now. I will search in the morning and report back.

**Comment by seandepagnier** [comment]
The issue is, that keypad_touch array isn't empty by default.     I will work on it to support multiple configurations.  How do you use the touchpad?  I would be really curious to see a picture of your setup.

   As for waking from a pin...  those boards unfortunately have external parts besides the esp32 so they cant sleep at super low power with software alone.     They are drawing hundreds of microamps which will drain a small battery in a few weeks.   To ensure the drain is below natural power loss unfortunately requires external mosfets so it can cut its own power.   Then wake from button pressed is also performed in hardware. 

The esp32 itself can sleep at low power but because of the usb-serial converter chip  it is not a very low power sleep.

**Comment by seandepagnier** [comment]
I will merge this by applying the patches..   Otherwise I am afraid the binary will still end up in the main fork.

**Comment by kagouraki** [comment]
So got some info about wake from touch:

```
import esp32
import machine
touch1=TouchPad(Pin(*someTouchPin*))
touch1.config(300) #touch threshold for a touch to be recognized as touched
esp32.wake_on_touch(True)
machine.deepsleep()
```

#####################################

Now i understand whats going on. You are planning to use the remote as a going around remote with a battery. I am just trying to avoid all the connections,wiring dissaster and 1.5meters limitation for the 3.3v signals from the display to the tinypilot pcb.
I will have the esp32 permanently mounted on the helm so power will not be a problem as it will be hardwired to the service battery. So i dont need deepsleep and shutdown. Also lag on boot(while performing thershold calibration) will not be a probelm because the tinypilot need some time to boot and create hotspots etc and they will be powerd on the same time when i flip the AUTOPILOT circuit breaker on the navstation. I also dont see the point of having a go around remote for pypilot because everyone has a smartphone to controll the pypilot from anywhere on the boat.

#####################################

Now i see where is the problem. I will commit and have the default keypad_touch array empty. The comments are self explanatory so if anyone wants to use it with touch, he will know what to do. Also i will commit and delete the bin file. 
 
####################################

As of how i am about to use it, i attach some pictures and my pcb files for a pcb i created. 
[https://github.com/kagouraki/tinypilot_pcb](url)

I have a two sided pcb in a aluminium waterproof box. On the top side are all the components and on the bottom side is the motor driver which is touching the box with custom aluminium block and thermal paste(to disipate heat through the box) and a thermistor to read temperature of motor driver. 
In the begining i wanted to have a jlx screen with ready made touchPadSwitchtes. The reason i go with touchpad is the ease of waterproofing the damn thing. As you see its difficult to wire all this in small space and i also have the short cable limitation of the screen and buttons signals. I think of making a pcb for the esp32 with a mini 360 dc-dc converter to supply 5v from 12v to the board. The esp32 will be soldered with the screen facing down the pcb with the pcb milled out where the screen is and the touchpads will be engraved in the pcb so no extra components will be needed. 7 Touchpads are enough for most cases. AUTO, MENU, SMALL_PORT, SMALL_STARBOARD, SELECT, BIG_PORT, BIG_STARBOARD.
My next concern of this project for me is that i need to separate the motor(arduino) part from the raspberry. So finally i will have three "boxes".
1. the esp32 remote on the helm
2. the motor(arduino) near the autopilot arm/hydralic/ tiller or what ever
3. the raspberry with the imu on the best spot in the middle and low as possible.

the communication between the raspberry and the arduino will be i think with a serial to rf communication(433Mhz). I havent tried this but i think it will work.

281515691_575265837272363_2607994151372972183_n
281636508_425106865730767_3165077755093467463_n
281833934_1634835890207299_7199176233544406580_n
281962089_2227598344075847_3947276566032339510_n
282060803_426207632232379_7363606010201677757_n
283639223_535234328194802_2720635261538322314_n

**Comment by seandepagnier** [comment]
Wow.

Instead of a wireless rf link to the motor controller, you can just use 24awg phone cable 4 conductor.

Otherwise.. keep it near, and run the power wires to the motor.   Either way has trade offs.

**Pull request closed without merging**
