### PR TITLE
Implement volts/amps correction by offset and gain compensation.

### PR DESCRIPTION
**Pull request by stelian42**
The offset and gain values are stored in EEPROM and can be modified
by the clients using special codes.

In addition, a few other parameters (max controller temp,
max motor temp, rudder range, max slew) are also stored in EEPROM
making the controller safe even if no client is connected.

### CODE REVIEW

**Comment by seandepagnier** [comment]
I will look at this closely in a few days.  Thanks for these.

I wonder if the temp limits and current limits should be in eeprom as
well?  What about rudder calibration?

**Comment by stelian42** [comment]
Yes, I think that all the 'max_values' in servo.py are better stored in eeprom.

The downside is that we need more responses from controller to pypilot in order to retrieve at launch the values stored in eeprom. This is what I've done for current/voltage correction values. 

If you're ok with that I'll implement those as well.

**Comment by stelian42** [comment]
Here you go. I've also changed servo.py to send the parameters even if the pilot is not engaged.

**Comment by seandepagnier** [comment]
I have merged this, then basically rewritten it.

The goal was so that older/newer controllers can still work with older/newer pypilot.

But also to reduce logic on the avr and make changing the format in  future versions easy without needing to flash the controller.

**Comment by Mrpergnant65** [comment]
Hi Sean

Now I did install in my small motor/sailboat, but instead of connect the drive unit to the wheel I did put it on the ruddershaft.

But now to a small problem, when I connected with the wireharness and the pilot starts up ok, there is no power from the controller?
Is there any setting that I need to do?
The drive motor is an old standalone autopilot with only DC motor and pushrod.

Thanks
Joakim Hvarfven

Skaffa Outlook för Android<https://aka.ms/ghei36>

________________________________

**Pull request closed without merging**
