### PR TITLE
add pypilot_calibration entry point

### PR DESCRIPTION
**Pull request by sailoog**

### CODE REVIEW

**Comment by sailoog** [comment]
do not merge second commit "temporally disabled features"

**Comment by seandepagnier** [comment]
looks good, except the wxforumbuilder generated code cannot be edited.

**Comment by sailoog** [comment]
Ok, those cosmetic changes are temporal and they will be reverted. I have disabled servo calibration until I finish implementing compass in OpenPlotter. I have pushed this just to suggest the entry point. I will publish a new OP soon, thanks for pypilot, it works!!

**Comment by seandepagnier** [comment]
Implemented

**Pull request closed without merging**
